# Challenge: Iterate and evaluate your classifier

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import gutenberg, stopwords
from collections import Counter
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import RFE

In [2]:
data_path = ('yelp_labelled.txt')
sms_raw = pd.read_csv(data_path, delimiter= '\t', header=None)
sms_raw.columns = ['message','like']

In [3]:
sms_raw['message'] = sms_raw['message'].str.lower()
sms_raw['message'] = sms_raw['message'].str.replace('!', '')
sms_raw['message'] = sms_raw['message'].str.replace('"', '')
sms_raw['message'] = sms_raw['message'].str.replace('$', '')
sms_raw['message'] = sms_raw['message'].str.replace("'", '')
sms_raw['message'] = sms_raw['message'].str.replace('%', '')
sms_raw['message'] = sms_raw['message'].str.replace('&', '')
sms_raw['message'] = sms_raw['message'].str.replace('(', '')
sms_raw['message'] = sms_raw['message'].str.replace(')', '')
sms_raw['message'] = sms_raw['message'].str.replace('*', '')
sms_raw['message'] = sms_raw['message'].str.replace('+', '')
sms_raw['message'] = sms_raw['message'].str.replace(',', '')
sms_raw['message'] = sms_raw['message'].str.replace('-', '')
sms_raw['message'] = sms_raw['message'].str.replace('.', '')
sms_raw['message'] = sms_raw['message'].str.replace('/', '')
sms_raw['message'] = sms_raw['message'].str.replace('0', '')
sms_raw['message'] = sms_raw['message'].str.replace('1', '')
sms_raw['message'] = sms_raw['message'].str.replace('2', '')
sms_raw['message'] = sms_raw['message'].str.replace('3', '')
sms_raw['message'] = sms_raw['message'].str.replace('4', '')
sms_raw['message'] = sms_raw['message'].str.replace('5', '')
sms_raw['message'] = sms_raw['message'].str.replace('6', '')
sms_raw['message'] = sms_raw['message'].str.replace('7', '')
sms_raw['message'] = sms_raw['message'].str.replace('8', '')
sms_raw['message'] = sms_raw['message'].str.replace('9', '')
sms_raw['message'] = sms_raw['message'].str.replace(':', '')
sms_raw['message'] = sms_raw['message'].str.replace(';', '')
sms_raw['message'] = sms_raw['message'].str.replace('?', '')

In [4]:
sms_raw1 = sms_raw.copy()
sms_raw2 = sms_raw.copy()
sms_raw3 = sms_raw.copy()
sms_raw4 = sms_raw.copy()
sms_raw5 = sms_raw.copy()
sms_raw6 = sms_raw.copy()

In [5]:
new_keywords1 = ['nice', 'back', 'great', 'friendly', 'delicious', 'dont', 'never', 'would', 'good', 'nice', 'time', 'staff',
            'restaurant', 'love', 'bad', 'amazing', 'disappointed', 'never', 'best', 'one', 'minutes', 'wont', 'wasnt',
            'amazing', 'always', 'made', 'pretty', 'loved', 'menu', 'slow', 'definitely']
new_keywords2 = ['restaurant', 'love', 'really', 'bad', 'amazing', 'disappointed', 'never', 'best', 'one', 'wont', 'wasnt',]
new_keywords3 = ['great', 'food', 'place', 'service', 'friendly', 'delicious', 'back', 'nice']
new_keywords4 = ['good', 'great', 'food', 'place', 'service', 'friendly', 'delicious', 'back', 'nice', 'like','go',
                 'dont', 'never', 'would']
new_keywords5 = ['food', 'place', 'back', 'service', 'like','go', 'dont', 'good', 'never', 'would']
new_keywords6 = ['bad', 'menu', 'pretty', 'amazing', 'delicious', 'dont', 'never', 'would', 'wasnt', 'wont', 'minutes', 'one',
                'never', 'disappointed', 'amazing', 'slow']
def addkey(text, keywords):
    for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
        text[str(key)] = text.message.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

In [6]:
addkey(sms_raw1, new_keywords1)
addkey(sms_raw2, new_keywords2)
addkey(sms_raw3, new_keywords3)
addkey(sms_raw4, new_keywords4)
addkey(sms_raw5, new_keywords5)
addkey(sms_raw6, new_keywords6)

In [7]:
data1 = sms_raw1[new_keywords1]
data2 = sms_raw2[new_keywords2]
data3 = sms_raw3[new_keywords3]
data4 = sms_raw4[new_keywords4]
data5 = sms_raw5[new_keywords5]
data6 = sms_raw6[new_keywords6]

In [8]:
target = sms_raw['like']

In [9]:
bnb = BernoulliNB()
X_train, X_test, y_train, y_test = train_test_split(data1, target, test_size=0.2, random_state=20)
bnb.fit(data1, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data1, target).score(data1, target)))

With 20% Holdout: 0.63
Testing on Sample: 0.651


In [10]:
y_pred1 = bnb.predict(data1)
confusion_matrix(target, y_pred1)

array([[465,  35],
       [314, 186]], dtype=int64)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(data2, target, test_size=0.2, random_state=20)
bnb.fit(data2, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data2, target).score(data2, target)))

With 20% Holdout: 0.56
Testing on Sample: 0.562


In [12]:
y_pred2 = bnb.predict(data2)
confusion_matrix(target, y_pred2)

array([[ 73, 427],
       [ 11, 489]], dtype=int64)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(data3, target, test_size=0.2, random_state=20)
bnb.fit(data3, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data3, target).score(data3, target)))

With 20% Holdout: 0.575
Testing on Sample: 0.572


In [14]:
y_pred3 = bnb.predict(data3)
confusion_matrix(target, y_pred3)

array([[495,   5],
       [423,  77]], dtype=int64)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(data4, target, test_size=0.2, random_state=20)
bnb.fit(data4, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data4, target).score(data4, target)))

With 20% Holdout: 0.595
Testing on Sample: 0.602


In [16]:
y_pred4 = bnb.predict(data4)
confusion_matrix(target, y_pred4)

array([[454,  46],
       [352, 148]], dtype=int64)

In [17]:
X_train, X_test, y_train, y_test = train_test_split(data5, target, test_size=0.2, random_state=20)
bnb.fit(data5, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data5, target).score(data5, target)))

With 20% Holdout: 0.52
Testing on Sample: 0.555


In [18]:
y_pred5 = bnb.predict(data5)
confusion_matrix(target, y_pred5)

array([[103, 397],
       [ 48, 452]], dtype=int64)

#### Do any of your classifiers seem to overfit?

No, their accuracy between test and train were all close

#### Which seem to perform the best? Why?

### data1 was my best classifier for this test it showed 63% accuracy in the training sample and over 65% with the test sample

#### Which features seemed to be most impactful to performance?

bad, menu, pretty, amazing, delicious, dont, never, would, wasnt, won't, minutes, one, never, disappointed, amazing, slow
While good and great helped find a lot of positives reviews it also gave a lot false positives

In [19]:
selectr1 = RFE(bnb)
selector1 = selectr1.fit(data1, target)
rankings1 = pd.DataFrame({'Features': data1.columns, 'Ranking' : selector1.ranking_})
rankings1.sort_values('Ranking')

Features  Ranking
15       amazing        1
23       amazing        1
22         wasnt        1
21          wont        1
20       minutes        1
19           one        1
17         never        1
16  disappointed        1
29          slow        1
14           bad        1
30    definitely        1
4      delicious        1
5           dont        1
6          never        1
7          would        1
26        pretty        2
11         staff        3
27         loved        4
24        always        5
25          made        6
28          menu        7
12    restaurant        8
13          love        9
1           back       10
18          best       11
9           nice       12
0           nice       13
10          time       14
3       friendly       15
2          great       16
8           good       17

In [20]:
bnb.fit(data6, target)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data6, target).score(data6, target)))

With 20% Holdout: 0.52
Testing on Sample: 0.602


In [21]:
y_pred6 = bnb.predict(data6)
confusion_matrix(target, y_pred6)

array([[124, 376],
       [ 22, 478]], dtype=int64)