# KNN regression

In [17]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cluster import KMeans
from sklearn import neighbors
from sklearn.model_selection import cross_val_score
music = pd.DataFrame()
music['duration'] = [184, 134, 243, 186, 122, 197, 294, 382, 102, 264, 
                     205, 110, 307, 110, 397, 153, 190, 192, 210, 403,
                     164, 198, 204, 253, 234, 190, 182, 401, 376, 102]
music['loudness'] = [18, 34, 43, 36, 22, 9, 29, 22, 10, 24, 
                     20, 10, 17, 51, 7, 13, 19, 12, 21, 22,
                     16, 18, 4, 23, 34, 19, 14, 11, 37, 42]
music['bpm'] = [ 105, 90, 78, 75, 120, 110, 80, 100, 105, 60,
                  70, 105, 95, 70, 90, 105, 70, 75, 102, 100,
                  100, 95, 90, 80, 90, 80, 100, 105, 70, 65]

In [18]:
knn = neighbors.KNeighborsRegressor(n_neighbors=10)
X = music[["loudness", "duration"]]
Y = music.bpm

knn.fit(X, Y)

T = pd.DataFrame({"Duration" : np.arange(0, 50, 0.1), "Loudness" : np.arange(0, 50, 0.1)})

knn.predict(T);

In [3]:
# weighted KNN
knn_w = neighbors.KNeighborsRegressor(n_neighbors=10, weights= 'distance')
knn_w.fit(X, Y)

T = pd.DataFrame({"Duration" : np.arange(0, 50, 0.1), "Loudness" : np.arange(0, 50, 0.1)})

knn.predict(T);

In [16]:
score = cross_val_score(knn, X, Y, cv=5)
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score.mean(), score.std() * 2))
score_w = cross_val_score(knn_w, X, Y, cv=5)
print("Weighted Accuracy: %0.2f (+/- %0.2f)" % (score_w.mean(), score_w.std() * 2))
print(score, score_w)

Unweighted Accuracy: -0.42 (+/- 0.78)
Weighted Accuracy: -0.26 (+/- 0.74)
[-0.19955242  0.02166018 -0.45898521 -1.12653237 -0.33925385] [-0.19928589  0.11602916 -0.03725669 -0.96209236 -0.24160284]
<bound method RegressorMixin.score of KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=10, p=2,
          weights='uniform')> 0.992882224542


In [10]:
knn2 = neighbors.KNeighborsRegressor(n_neighbors=6)
knn2.fit(X, Y)
knn_w2 = neighbors.KNeighborsRegressor(n_neighbors=6, weights= 'distance')
knn_w2.fit(X, Y);

In [11]:
score2 = cross_val_score(knn2, X, Y, cv=5)
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score2.mean(), score2.std() * 2))
score_w2 = cross_val_score(knn_w2, X, Y, cv=5)
print("Weighted Accuracy: %0.2f (+/- %0.2f)" % (score_w2.mean(), score_w2.std() * 2))
print(score2, score_w2)

Unweighted Accuracy: -0.51 (+/- 0.81)
Weighted Accuracy: -0.37 (+/- 0.88)
[-0.27589046  0.10333333 -1.0264332  -0.84676259 -0.52029915] [-0.22433116  0.17544965 -0.31339279 -1.1755091  -0.31833106]


In [12]:
knn3 = neighbors.KNeighborsRegressor(n_neighbors=4)
knn3.fit(X, Y)
knn_w3 = neighbors.KNeighborsRegressor(n_neighbors=4, weights= 'distance')
knn_w3.fit(X, Y);

In [14]:
score3 = cross_val_score(knn3, X, Y, cv=5)
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score3.mean(), score3.std() * 2))
score_w3 = cross_val_score(knn_w3, X, Y, cv=5)
print("Weighted Accuracy: %0.2f (+/- %0.2f)" % (score_w3.mean(), score_w3.std() * 2))
print(score3, score_w3)

Unweighted Accuracy: -0.84 (+/- 1.25)
Weighted Accuracy: -0.63 (+/- 1.64)
[-0.58770161 -0.09586283 -1.08214008 -1.93219424 -0.52403846] [-0.36797107  0.05419452 -0.29107565 -2.24753038 -0.32141451]


In [15]:
knn4 = neighbors.KNeighborsRegressor(n_neighbors=3)
knn4.fit(X, Y)
knn_w4 = neighbors.KNeighborsRegressor(n_neighbors=3, weights= 'distance')
knn_w4.fit(X, Y);
score4 = cross_val_score(knn4, X, Y, cv=5)
print("Unweighted Accuracy: %0.2f (+/- %0.2f)" % (score4.mean(), score4.std() * 2))
score_w4 = cross_val_score(knn_w4, X, Y, cv=5)
print("Weighted Accuracy: %0.2f (+/- %0.2f)" % (score_w4.mean(), score_w4.std() * 2))

Unweighted Accuracy: -0.69 (+/- 1.03)
Weighted Accuracy: -0.59 (+/- 1.75)
[-0.18723118 -0.12106195 -0.95071336 -1.51159073 -0.68589744] [-0.08085886  0.01328205 -0.22958188 -2.31848052 -0.31762584]


The knn3 model seems to be the better of the bunch, however the variance is still extremely bad.