In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

C:\Users\blindside\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
y2015.head()

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  68009401  72868139.0    16000.0      16000.0          16000.0   60 months   
1  68354783  73244544.0     9600.0       9600.0           9600.0   36 months   
2  68466916  73356753.0    25000.0      25000.0          25000.0   36 months   
3  68466961  73356799.0    28000.0      28000.0          28000.0   36 months   
4  68495092  73384866.0     8650.0       8650.0           8650.0   36 months   

  int_rate  installment grade sub_grade            ...              \
0   14.85%       379.39     C        C5            ...               
1    7.49%       298.58     A        A4            ...               
2    7.49%       777.55     A        A4            ...               
3    6.49%       858.05     A        A2            ...               
4   19.89%       320.99     E        E3            ...               

  num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75  \
0                0.0                2.0           78.9               0.0   
1                0.0                2.0          100.0              66.7   
2                0.0                0.0          100.0              20.0   
3                0.0                0.0           91.7              22.2   
4                0.0               12.0          100.0              50.0   

  pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort  \
0                  0.0       2.0        298100.0           31329.0   
1                  0.0       0.0         88635.0           55387.0   
2                  0.0       0.0        373572.0           68056.0   
3                  0.0       0.0        304003.0           74920.0   
4                  1.0       0.0         38998.0           18926.0   

  total_bc_limit total_il_high_credit_limit  
0       281300.0                    13400.0  
1        12500.0                    75635.0  
2        38400.0                    82117.0  
3        41500.0                    42503.0  
4         2750.0                    18248.0  

[5 rows x 111 columns]

In [4]:
y2015.tail()

id   member_id  \
421092                                          36271333  38982739.0   
421093                                          36490806  39222577.0   
421094                                          36271262  38982659.0   
421095  Total amount funded in policy code 1: 6417608175         NaN   
421096  Total amount funded in policy code 2: 1944088810         NaN   

        loan_amnt  funded_amnt  funded_amnt_inv        term int_rate  \
421092    13000.0      13000.0          13000.0   60 months   15.99%   
421093    12000.0      12000.0          12000.0   60 months   19.99%   
421094    20000.0      20000.0          20000.0   36 months   11.99%   
421095        NaN          NaN              NaN         NaN      NaN   
421096        NaN          NaN              NaN         NaN      NaN   

        installment grade sub_grade            ...              \
421092       316.07     D        D2            ...               
421093       317.86     E        E3            ...               
421094       664.20     B        B5            ...               
421095          NaN   NaN       NaN            ...               
421096          NaN   NaN       NaN            ...               

       num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75  \
421092                0.0                3.0          100.0              50.0   
421093                1.0                2.0           95.0              66.7   
421094                0.0                1.0          100.0              50.0   
421095                NaN                NaN            NaN               NaN   
421096                NaN                NaN            NaN               NaN   

       pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort  \
421092                  1.0       0.0         51239.0           34178.0   
421093                  0.0       0.0         96919.0           58418.0   
421094                  0.0       1.0         43740.0           33307.0   
421095                  NaN       NaN             NaN               NaN   
421096                  NaN       NaN             NaN               NaN   

       total_bc_limit total_il_high_credit_limit  
421092        10600.0                    33239.0  
421093         9700.0                    69919.0  
421094        41700.0                        0.0  
421095            NaN                        NaN  
421096            NaN                        NaN  

[5 rows x 111 columns]

In [5]:
y2015 = y2015[:-2]

In [6]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421095
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
12
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


In [8]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [16]:
pd.get_dummies(y2015);

In [10]:
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([ 0.98078887,  0.98038517,  0.98159626,  0.98178623,  0.97302303,
        0.97748753,  0.93488328,  0.98066922,  0.98016957,  0.98045409])

In [20]:
X = y2015[['loan_amnt', 'int_rate', 'annual_inc', 'dti', 'installment',
           'term', 'pub_rec_bankruptcies', 'total_bc_limit',  'total_il_high_credit_limit']]
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)
cross_val_score(rfc, X, Y, cv=10)

array([ 0.65564817,  0.65127876,  0.65512574,  0.65301228,  0.65155545,
        0.64880076,  0.64867368,  0.64553896,  0.64326597,  0.60048449])

In [25]:
X = y2015[['loan_amnt', 'int_rate', 'annual_inc', 'dti', 'installment', 'grade', 'tax_liens', 'percent_bc_gt_75', 'home_ownership'
           'term', 'pub_rec_bankruptcies', 'total_bc_limit',  'total_il_high_credit_limit', 'verification_status']]
X = pd.get_dummies(X)
X = X.dropna(axis=1)
cross_val_score(rfc, X, Y, cv=10)

array([ 0.66072998,  0.65135   ,  0.65586189,  0.65410463,  0.65264783,
        0.64975065,  0.64800874,  0.64078938,  0.63777994,  0.55343656])